### ISSUE TITLE
对超长文本进行总结的例子，执行时报错

### ISSUE THREAD

**Issue by clgwlg** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#11]
## 错误信息
Traceback (most recent call last):
  File "/main.py", line 56, in <module>
    chain.run(split_documents[:5])
  File "/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 238, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
  File "/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 136, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/venv/lib/python3.9/site-packages/langchain/chains/combine_documents/base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "/venv/lib/python3.9/site-packages/langchain/chains/combine_documents/refine.py", line 94, in combine_docs
    res = self.initial_llm_chain.predict(callbacks=callbacks, **inputs)
  File "/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 136, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/venv/lib/python3.9/site-packages/langchain/chains/llm.py", line 79, in generate
    return self.llm.generate_prompt(
  File "/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 127, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
  File "/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 176, in generate
    raise e
  File "/venv/lib/python3.9/site-packages/langchain/llms/base.py", line 170, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "/venv/lib/python3.9/site-packages/langchain/llms/openai.py", line 306, in _generate
    response = completion_with_retry(self, prompt=_prompts, **params)
  File "/venv/lib/python3.9/site-packages/langchain/llms/openai.py", line 106, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/venv/lib/python3.9/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/langchain/llms/openai.py", line 104, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "/venv/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/liangchen/PycharmProjects/langchain/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 113, in __prepare_create_request
    url = cls.class_url(engine, api_type, api_version)
  File "/venv/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
    raise error.InvalidRequestError(
TypeError: __init__() missing 1 required positional argument: 'param'

**Comment by clgwlg** [comment]
问题已解决，AzureOpenAI传入的参数缺失导致
