### ISSUE TITLE
加载youtub视频的例子，原样复制代码本地执行，第二个提问之后就报错了

### ISSUE THREAD

**Issue by rongweihe** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#26]
Using embedded DuckDB without persistence: data will be transient
问题：这个视频主要讲了啥
这个视频主要展示了 Unreal Engine 5.2 引擎的一些新实验性功能，包括支持植被渲染、物理模拟、流体模拟、材质框架等。视频中展示了一个真实感极强的环境，包括一辆 Rivian R1T 电动皮卡车，通过引擎的实时渲染技术和物理模拟技术，展示了车辆的悬挂、轮胎变形、声音合成等效果。视频还介绍了引擎内置的一套实验性的程序化内容生成工具，可以帮助艺术家快速生成场景中的元素，并且可以与其他程序化元素进行交互。
问题：植被渲染有哪些场景
Traceback (most recent call last):
  File "load_ytb.py", line 67, in <module>
    result = qa({'question': question, 'chat_history': chat_history})
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/conversational_retrieval/base.py", line 101, in _call
    new_question = self.question_generator.run(
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 123, in __call__
    inputs = self.prep_inputs(inputs)
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 216, in prep_inputs
    self._validate_inputs(inputs)
  File "/Users/xx/.pyenv/versions/3.8.6/lib/python3.8/site-packages/langchain/chains/base.py", line 83, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'context'}

**Comment by liaokongVFX** [comment]
应该是这个类后续被修改了，我周末抽空改下这块的案例

**Comment by thiswind** [comment]
> 应该是这个类后续被修改了，我周末抽空改下这块的案例

我觉得是模板写错了，把模板改成

```python
system_template = """
Use the following context to answer the user's question.
If you don't know the answer, say you don't, don't try to make it up. And answer in Chinese.
-----------
{question}
-----------
{chat_history}
"""
```

即把 `{context}` 改成 `{question}`，就可以了。
