### ISSUE TITLE
使用GPT3.5模型构建油管频道问答机器人 这个demo里面的system_template 里面的${content}是不是写错了，应该是${question}，提问后会报错 ValueError: Missing some input keys: {'context'}

### ISSUE THREAD

**Issue by altraman00** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#36]
使用GPT3.5模型构建油管频道问答机器人 这个demo里面的system_template 里面的${content}是不是不对，

问题：水蓝心的妈妈是谁
Traceback (most recent call last):
  File "/Users/knight/workspace/sourceTree/mobvoi/aitoc_competent/api_lc/app/example/7_lc.py", line 72, in <module>
    result = qa({'question': question, 'chat_history': chat_history, 'context': context})
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 101, in _call
    new_question = self.question_generator.run(
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 123, in __call__
    inputs = self.prep_inputs(inputs)
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 216, in prep_inputs
    self._validate_inputs(inputs)
  File "/Users/knight/miniconda3/envs/py310/lib/python3.10/site-packages/langchain/chains/base.py", line 83, in _validate_inputs
    raise ValueError(f"Missing some input keys: {missing_keys}")
ValueError: Missing some input keys: {'context'}

Process finished with exit code 1

**Comment by henryYu1103** [comment]
是的， 换成 {question} 就好了

**Comment by lilee** [comment]
不应该换成question啊，question在下面有定义
