### ISSUE TITLE
第一个例子报错了呢

### ISSUE THREAD

**Issue by anyuanzhao** [liaokongVFX/LangChain-Chinese-Getting-Started-Guide#4]
第一个例子就报错了呢？
代码：
import os

os.environ["OPENAI_API_KEY"] = "sk-aaa"
os.environ["SERPAPI_API_KEY"] = "aaaa"

from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.llms import OpenAI
from langchain.agents import AgentType

llm = OpenAI(temperature=0, max_tokens=2048)

tools = load_tools(["serpapi"])

agent = initialize_agent(tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True)

agent.run("What's the date today? What great events have taken place today in history?")

报错：
Traceback (most recent call last):
  File "/Users/one/OpenAI/pythonProject3/main.py", line 24, in <module>
    agent = initialize_agent(tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True)
  File "/Users/one/OpenAI/pythonProject3/venv/lib/python3.9/site-packages/langchain/agents/initialize.py", line 52, in initialize_agent
    agent_obj = agent_cls.from_llm_and_tools(
  File "/Users/one/OpenAI/pythonProject3/venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 506, in from_llm_and_tools
    cls._validate_tools(tools)
  File "/Users/one/OpenAI/pythonProject3/venv/lib/python3.9/site-packages/langchain/agents/self_ask_with_search/base.py", line 34, in _validate_tools
    raise ValueError(
ValueError: Tool name should be Intermediate Answer, got {'Search'}

**Comment by anyuanzhao** [comment]
看样子，是：
agent = initialize_agent(tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True)
AgentType.SELF_ASK_WITH_SEARCH
这个不对

**Comment by liaokongVFX** [comment]
抱歉，感谢指出，已修正。当时只改了colab，忘改文章了。

agent type 需要使用`AgentType.ZERO_SHOT_REACT_DESCRIPTION`

```python
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
```
